name: github_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  fluttertoast: ^8.0.7
  http: ^0.13.3
  double_back_to_close: ^2.0.0
  shimmer: ^2.0.0
  intl: ^0.17.0
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  url_launcher: ^6.0.0
  # Default
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_github_edited.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf  
